# Generated by Django 4.1.7 on 2023-03-28 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'ordering': ('title',), 'verbose_name_plural': 'Yangiliklar'},
        ),
    ]
