# Generated by Django 4.1.7 on 2023-04-01 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_articles_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'ordering': ('-created_at',), 'verbose_name': 'Maqola', 'verbose_name_plural': 'Maqolalar'},
        ),
    ]
